---
title: "Geographic and Social Predictors of Readmission."
author: "Author One 1, …, …, …, Pseudonym Elemental PhD, MD 1,✉"
date: "11/17/2021"
output: html_document
---

# 4. Download the data set programatically
```{r}
library(openxlsx);
census2015 <- read.xlsx('https://www.ahrq.gov/sites/default/files/wysiwyg/sdohchallenge/data/SDOH_ZCTA_2015.xlsx');
ahrqCodebook2015 <- read.xlsx('https://www.ahrq.gov/sites/default/files/wysiwyg/sdohchallenge/data/sdoh_codebook_final.xlsx', sheet ='ZCTA_2015');
sdi <- read.xlsx('https://www.graham-center.org/content/dam/rgc/documents/maps-data-tools/sdi/ACS2015_zctaallvars.xlsx');
library(readr);
outcomes <- read_csv('data/OutcomeData.csv');
```

# 5. Merge and get into the same format
```{r}
# check colnames
colnames(census2015)
colnames(ahrqCodebook2015)
colnames(sdi)
colnames(outcomes)

# change colnames
colnames(ahrqCodebook2015);
toupper(colnames(ahrqCodebook2015))
colnames(ahrqCodebook2015) <- toupper(colnames(ahrqCodebook2015))
colnames(sdi);
toupper(colnames(sdi))
colnames(sdi) <- toupper(colnames(sdi))

# finding the overlapped colnames
intersect(colnames(census2015), colnames(ahrqCodebook2015))
intersect(colnames(census2015), colnames(sdi)) # 1
intersect(colnames(census2015), colnames(outcomes)) # 1
intersect(colnames(ahrqCodebook2015), colnames(sdi))
intersect(colnames(ahrqCodebook2015), colnames(outcomes))
intersect( colnames(sdi), colnames(outcomes)) # 1

# merge data
df <- merge(outcomes, census2015, by = intersect(colnames(census2015), colnames(outcomes)), all.x = TRUE)
dat0 <- merge(df, sdi, by = intersect(colnames(df), colnames(sdi)), all.x = TRUE)
```

# 6. Prepare analytical data set
## 6.a. Assign records to training and testing subset (#3)
## 6.b. Find sample sizes for test and train (#4)
```{r}
dat0$sample <- sample(c("train", "test"), nrow(dat0), rep=T, prob = c(1/2, 1/2)) 
dtrain <- subset(dat0, sample == "train")
dtest <- subset(dat0, sample=="test")
nrow(dtrain)
nrow(dtest)
```

7. Fit a regression model
7.a. Null model, no predictors 
```{r}
# Stepwise Regression Essentials in R
library(tidyverse)
library(caret)
# install.packages("leaps")
library(leaps)

# Bayes information criterion (BIC)

lm1 <- lm(NoReadmission ~ 1 , data = dtrain)# null model
summary(lm1)
lmf <- lm(NoReadmission ~ . , data = dtrain)# full model
M1.step <- step(lm1, 
                scope = list(lower = NoReadmission ~ 1, 
                             upper = NoReadmission ~ .),
               direction = "both", k = log(nrow(dtrain)))

AIC(lm1)
BIC(lm1)
```

